image:
  file: .gitpod.Dockerfile
tasks:
  - init: cd cmake-build-debug && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . -j$(nproc)
    command: ./funscript
vscode:
  extensions:
    - webfreak.debug