name: Debug build and tests
on: [ push ]
jobs:
  Build-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install latest GNU C and C++ compilers
        run: sudo apt update && sudo apt install gcc g++
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Generate CMake build files
        run: cd cmake-build-debug; cmake -DCMAKE_BUILD_TYPE=Debug ..
        env:
          CC: gcc
          CXX: g++
      - name: Build project
        run: cd cmake-build-debug; make -j$(nproc)
      - name: Run tests
        run: cd cmake-build-debug; make test